#! /bin/sh

if [ $# = 0 ]; then
  echo "`basename $0` file <passfile>"
  exit
fi
if [  -d "$1" ]; then
  echo "'$1' is a directory"
  exit
fi
if [  ! -f "$1" ]; then
  echo "file '$1' does not exist"
  exit
fi
PFILE=""
if [ $# -eq 2 ]; then
  PFILE="-pass file:$2"
fi
case "$1" in
  *.enc)
    openssl enc $PFILE -d -aes-256-cbc -a -in "$1" -out "$(basename "$1" .enc)"
    ;;
  *)
    openssl enc $PFILE -aes-256-cbc -a -in "$1" -out "$1.enc"
    ;;
esac
